---
- name: "Generate kickstart OEMDRV ISOs"
  hosts: provisioner
  become: true
  gather_facts: false

  tasks:

    - name: "Load the vault directory variables files"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load vault file variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the vars directory variables files"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Load vars file variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Apply role bootstrap_init"
      when: bootstrap_init_hosts is defined and (bootstrap_init_hosts | length) > 0
      ansible.builtin.include_role:
        name: "bootstrap_init"
